### ISSUE TITLE
Server tests are failing when calling _cc_pipeline directly

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#1981]
**Describe the issue**
The 2 new tests introduced in #1957 are failing as a result of changes made in #1968. The `get_display_name()` function introduced in the latter PR expects a `ContainerOp` object whereas the tests create a `TaskSpec` object. The disconnect appears to happen due to some of the internals of the KFP compiler that we do not have access to.

Related to #1756 as well.

**Screenshots or log output**
Test failure output is below.
<details><summary>Log Output</summary>
<pre>
Error constructing component Filter text: 'TaskSpec' object has no attribute 'set_display_name'</pre>
</details>

**Expected behavior**
Eventually, all invocations of _cc_pipeline() should produce the same output. For now, we'll skip these tests.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: latest master

**Comment by akchinSTC** [comment]
Added some in-line comments as workarounds i.e black boxing the compiler and asserting against the pipeline file afterwards

```
# We arent able to access the container op level here since the runtime component is a taskspec
    constructed_pipeline_function = lambda: processor._cc_pipeline(pipeline=pipeline, pipeline_name='test_pipeline')

    # We can check again both argo and tekton compilations
    # we can check the pipeline file for `correctness`
    compiled_pipeline = kfp_argo_compiler.Compiler().compile(constructed_pipeline_function, pipeline_path)

    ```
