### ISSUE TITLE
Markdown versions 3.4.0 and 3.4.1 break documentation build

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#2837]
**Describe the issue**
Markdown [released a new version](https://pypi.org/project/Markdown/3.4/#history) that caused our doc builds to fail both locally and in the CI with:

```
Extension error (sphinx_markdown_tables):
Handler <function process_tables at 0x7fdd2d294790> for event 'source-read' threw an exception (exception: __init__() missing 1 required positional argument: 'config')
```
See here for more: https://github.com/elyra-ai/elyra/runs/7362961491?check_suite_focus=true.

Note that `Markdown==3.4.1` does not solve this issue. #2836 caps `Markdown` to `v<3.4`, but this is a temporary solution.

One potential solution is to remove the doc dependency on `sphinx-markdown-tables`. When testing locally with `sphinx-markdown-tables` uninstalled, tables appear to still be rendered correctly for some whereas others see something like the below. Further investigation needs to be done to determine the reason for this and whether this could provide an eventual solution.

<img width="727" alt="Screen Shot 2022-07-15 at 4 33 32 PM" src="https://user-images.githubusercontent.com/31816267/179314046-b8c7bd95-9c75-4168-93bb-256995920b12.png">

**Comment by kevin-bates** [comment]
Much to my surprise, version 0.0.16 of `sphinx-markdown-tables` was released yesterday and works with `Markdown` >= 3.4.1.  PR forthcoming to adjust min versions.  We can talk about moving to `myst-parser` another time.
