### PR TITLE
Move build system to use pyproject.toml

### PR DESCRIPTION
**Pull request by akchinSTC**
Signed-off-by: Alan Chin <akchin@us.ibm.com>

- removed MANIFEST.in, setup.cfg, pytest.ini
- use hatch engine instead of setuptools
- moved labextension output directory due to hatch requirements (will not allow artifacts in dist dir to be placed in sdist)

TODO:

- [x] update release script
- [x] verify tests still function
- [x] address codeql issues
~~- [ ] setup build hooks for lab extensions (stretch)~~

### How was this pull request tested?

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by akchinSTC** [comment]
> @akchinSTC - the primary changes from #3032 are not present here. I suspect this is because you had started this work prior to the merge of 3032 and since this PR removes `pytest.ini` and 3032 added a bunch of entries to it, the file's deletion takes precedence over content-reconciliation. As a result, the entries in 3032 (and any other recently merged PRs that might have modified files deleted in this PR) should have those changes added to their new locations in `pyproject.toml`.

Thanks, I was totally rushing and missed that during the rebase

File: pyproject.toml [hunk 1]
```diff
@@ -1,6 +1,268 @@
...
+    "Operating System :: OS Independent",
+    "Topic :: Scientific/Engineering",
+    "Topic :: Scientific/Engineering :: Artificial Intelligence",
+    "Topic :: Software Development",
+    "Topic :: Software Development :: Libraries",
+    "Topic :: Software Development :: Libraries :: Python Modules",
+    "Programming Language :: Python :: 3.7",
+    "Programming Language :: Python :: 3.8",
+    "Programming Language :: Python :: 3.9",
+    "Programming Language :: Python :: 3.10",
```
Comment (kevin-bates) [inline pyproject.toml:65]: Looks like this change from #3033 wasn't applied.
```suggestion
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
```

File: pyproject.toml [hunk 2]
```diff
@@ -1,6 +1,268 @@
...
+]
+import-order-style = "google"
+
+# Configuration parameters for the black code formatting tool
 [tool.black]
 # max line length; same as 'max-line-length' in setup.cfg
 line-length = 120
 
 # Python versions that should be supported by the produced output
 target-version = ['py37', 'py38', 'py39', 'py310']
```
Comment (kevin-bates) [inline pyproject.toml:226]: Although not added in #3033, we should include a 3.11 reference...
```suggestion
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
```

File: pyproject.toml [hunk 3]
```diff
@@ -1,6 +1,269 @@
...
+Documentation = "https://elyra.readthedocs.io/en/latest"
+Homepage = "https://github.com/elyra-ai/elyra"
+
+[project.optional-dependencies]
+test = [
+    "elyra-examples-kfp-catalog",
+    "git-python",
+    "importlib-resources",
+    "pytest>=5.4.1",
+    "pytest-console-scripts",
```
Comment (kevin-bates) [inline pyproject.toml:80]: Could we go ahead and add `pytest_jupyter` to get ahead of the server 2.0 release?  Once 2.0 is released (slated for Monday), our pytests will fail because the jupyter server pytest plugins we use will be provided by `pytest_jupyter` rather than `jupyter_server` directly.  I could go ahead and deliver a PR, but it will be essentially moot since it will be updating a location that will be obsoleted by this PR.
```suggestion
    "pytest-console-scripts",
    "pytest_jupyter",
```
I've confirmed our tests with `pytest_jupyter` installed, along with the _existing_ (pre 2.0) `jupyter_server` installed, still work.  So the presence of `pytest_jupyter` does not interfere with older `jupyter_server` installations.

File: lint_requirements.txt [hunk 4]
```diff
@@ -1,5 +1,6 @@
-black[jupyter]<=21.12b0
-click<=8.0.4
+black[jupyter]<=22.8.0
```
[the remark this answers is not in the document]
Comment (akchinSTC) [reply lint_requirements.txt:1]: > Is this cap necessary?

Thats a typo on part, supposed to be a floor not a cap. We need 22.8.0 or higher to support py 3.11. 

> should they be moved into the "build-system.requires" array in `pyproject.toml`

For this to work, I think we would need to switch the build targets to first build, then lint?

File: pyproject.toml (hunk 3 above)
Comment (akchinSTC) [reply pyproject.toml:80]: added

File: lint_requirements.txt (hunk 4 above)
[the remark this answers is not in the document]
Comment (kevin-bates) [reply lint_requirements.txt]: Ok - we can look into this another time.  Thanks!

File: pyproject.toml [hunk 5]
```diff
@@ -1,6 +1,270 @@
...
+    "jupyter-packaging>=0.10",
+    "jupyter_server>=1.7.0",
+    "jupyterlab>=3.4.6",  # comment out to use local jupyterlab
+    "jupyterlab-lsp>=3.8.0",  # comment out to use local jupyterlab
+    "jupyterlab-git~=0.32",  # Avoid breaking 1.x changes
+    "jupyter-resource-usage>=0.5.1",
+    "MarkupSafe>=2.1",
+    "minio>=7.0.0",
+    "nbclient>=0.5.1",
+    "nbconvert>=6.4.5",
```
Comment (kevin-bates) [inline pyproject.toml:34]: Should we bump this floor to `6.5.1` due to recent [dependency bot warnings](https://github.com/elyra-ai/elyra/security/dependabot/76).  Although this warning is relative to the test-requirements file, it should also apply to general installation requirements.

To that point, it looks like [the floor on `jupyter_core` should be increased to `4.11.2`](https://github.com/elyra-ai/elyra/security/dependabot/81) as well.

**Comment by ajbozarth** [comment]
From a front end build perspective this look good, I also tested the dev on local lab functionality and it works with these changes, but this doc will need to be updated since the location of some of the lines that need to be edited has changed https://elyra.readthedocs.io/en/latest/developer_guide/development-workflow.html#developing-elyra-against-the-jupyterlab-source-repo

File: pyproject.toml [hunk 6]
```diff
@@ -1,6 +1,270 @@
...
+requires-python = ">=3.7"
+dependencies = [
+    "autopep8>=1.5.0",
+    "click>=8",  # elyra-ai/elyra#2579
+    "colorama",
+    "deprecation",
+    "entrypoints>=0.3",
+    "jinja2>=3",
+    "jsonschema>=3.2.0,<4.0",  # Cap from kfp
+    "jupyter_core>=4.6.0",
```
Comment (kevin-bates) [inline pyproject.toml:23]:
```suggestion
    "jupyter_core>=4.11.2",
```

File: pyproject.toml (hunk 5 above)
Comment (kevin-bates) [inline pyproject.toml:34]:
```suggestion
    "nbconvert>=6.5.1",
```

**Comment by akchinSTC** [comment]
@kevin-bates - if you're still lurking around. 

Had to cap a few items in the last commit in this PR before merging
- Cap on jupyter-core due to v5+ not supporting 3.7. (temp until we stop as well)
- Cap on jupyter events due to kfp not supporting jsonschema v4
- Cap on jupyter_server_terminals due to >0.4.0 causing issues with installation. See output below. I dont think we actually need this yet since it looks like its a dependency for jupyter_server v2. Unfortunately I think its getting pulled in during dependency resolution. 

Will open issue to track if this is an ok workaround.
```
$ jupyter server extension list

Config dir: /Users/akchin/.jupyter

/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server_terminals/__init__.py:8: UserWarning: Could not import submodules
  warnings.warn("Could not import submodules")
Traceback (most recent call last):
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 320, in add_extension
    extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 166, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/traitlets/traitlets.py", line 1357, in __init__
    value = self._traits[key]._cross_validate(self, getattr(self, key))
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/traitlets/traitlets.py", line 743, in _cross_validate
    value = obj._trait_validators[self.name](obj, proposal)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/traitlets/traitlets.py", line 1229, in __call__
    return self.func(*args, **kwargs)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 175, in _validate_name
    self._module, self._metadata = get_metadata(name)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/utils.py", line 58, in get_metadata
    return module, module._jupyter_server_extension_points()
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server_terminals/__init__.py", line 15, in _jupyter_server_extension_points
    "app": TerminalsExtensionApp,
NameError: name 'TerminalsExtensionApp' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/akchin/opt/anaconda3/envs/remove/bin/jupyter-server", line 8, in <module>
    sys.exit(main())
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2814, in start
    self.start_app()
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2710, in start_app
    super().start()
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_core/application.py", line 258, in start
    self.subapp.start()
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/serverextension.py", line 368, in start
    super().start()
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_core/application.py", line 258, in start
    self.subapp.start()
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/serverextension.py", line 342, in start
    self.list_server_extensions()
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/serverextension.py", line 323, in list_server_extensions
    config_dir, ext_manager = _get_extmanager_for_context(**option)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/serverextension.py", line 59, in _get_extmanager_for_context
    extension_manager = ExtensionManager(
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/traitlets/config/configurable.py", line 86, in __init__
    super().__init__(**kwargs)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/traitlets/traitlets.py", line 1364, in __init__
    self.notify_change(changes[key])
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/traitlets/traitlets.py", line 1513, in notify_change
    return self._notify_observers(change)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/traitlets/traitlets.py", line 1560, in _notify_observers
    c(event)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 253, in _config_manager_changed
    self._load_config_manager(change.new)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 308, in _load_config_manager
    self.from_jpserver_extensions(jpserver_extensions)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 313, in from_jpserver_extensions
    self.add_extension(name, enabled=enabled)
  File "/Users/akchin/opt/anaconda3/envs/remove/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 325, in add_extension
    if self.serverapp.reraise_server_extension_failures:
AttributeError: 'NoneType' object has no attribute 'reraise_server_extension_failures'
make: *** [check-install] Error 1
```

**Review by ptitzler — APPROVED** [review]
LGTM! confirmed successful builds using 3.7-3.11

**Comment by kevin-bates** [comment]
Thanks for moving forward with this PR in my absence.

1. The `jupyter_server_terminals` issue looks like a server-related issue.  I can try to look into this upon my return, not a big deal to cap that for now.
2. The `jupyter_events` cap due (indirectly) to `kfp` is concerning.  This will prevent others from using Elyra alongside event-related functionality (not a big deal right now) and we may very well want to use the event system ourselves as well.  We should probably create an issue to revisit the `jsonschema` cap and how `kfp` v1 and `jupyter_events` can co-exist.
3. The introduction of `write_error()` calling the mixin's `write_error()` strikes me as unnecessary - and I thought I left had left a comment to this affect, but either it was blown away by a forced push or I forgot to save it.  Was the need for this triggered by a linting issue?  The Mixin's `write_error()` implementation should resolve and prevent the need for the override.

**Comment by akchinSTC** [comment]
> 1. The `jupyter_server_terminals` issue looks like a server-related issue.  I can try to look into this upon my return, not a big deal to cap that for now.

@kevin-bates - Sorry for bothering you on vacation. Yeah this package is causing some headaches atm. pips resolver continues to pull in jupyter_server >2, thus pulling in this package causing issues. Capping the issue still doesnt resolve the issue, as a result terminals are not working in the latest 3.14 release. Need a way avoid pulling jupyter_server >2 completely. I have tried capping it but the resolver still pulls in jupyter_server > 2......then.....resolves and installs the capped version...leaving the problematic dependency in place.
